<a href="https://colab.research.google.com/github/jacedoe/pythoniso/blob/main/Curso_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1.
Crea una lista de números secuenciales con el valor mínimo de 10 y el valor máximo de 39. Convierte esta lista en una lista o matriz de 2 dimensiones (3 filas por 10 columnas). Muestra por pantalla el valor del elemento de la esquina superior derecha.


Machine Learning. Curso básico de Machine Learning y Python de IBM Skillbuilds

Ejemplo Función Filter

In [ ]:
def positivo(num):
    if (num >= 0):
        return num
    else:
        return None
lista = [1,-1,2,-2,3,-3]
lista2 = list(filter(positivo,lista))
lista2

[1, 2, 3]

Ejemplo Función Map

In [2]:
def dividir_entre_dos(num):
    return num/2
lista = [1,2,3,4,5]
lista2 = list(map(dividir_entre_dos,lista))
lista2


[0.5, 1.0, 1.5, 2.0, 2.5]

Ejemplos con Numpy

In [4]:
import numpy as np
lista = [1,2,3,4,5]
array = np.array(lista)
array

array([1, 2, 3, 4, 5])

In [8]:
lista2 = ([1,2,3],[4,5,6],[7,8,9])
array2 = np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array = np.arange(0,10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
array[array > 5]


array([6, 7, 8, 9])

In [24]:
array[array % 2 == 1]


array([1, 3, 5, 7, 9])

In [31]:
array2 = np.arange(9,19)
array2


array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [32]:
array2 - array


array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

Ejercicio 1.
Crea una lista de números secuenciales con el valor mínimo de 10 y el valor máximo de 39. Convierte esta lista en una lista o matriz de 2 dimensiones (3 filas por 10 columnas). Muestra por pantalla el valor del elemento de la esquina superior derecha.

In [39]:
import numpy as np

sequential_list = list(range(10, 40))
two_dimensional_array = np.array(sequential_list).reshape(3, 10)
print(two_dimensional_array)

# Accessing the element in the top-right corner (first row, last column)
top_right_element = two_dimensional_array[0, 9]
print("Valor del elemento de la esquina superior derecha:", top_right_element)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
Valor del elemento de la esquina superior derecha: 19
